version: '2.3'
services:
  jekyll:
    image: jekyll/builder:3.8.5
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
    entrypoint: jekyll serve --livereload --incremental

